config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#home'
  resources :users
  resources :moods
  get '/user_login' => 'session#new'
  post '/user_login' => 'session#create'
  delete '/user_login' => 'session#destroy'


  get '/login' => 'playlist#login'
  get '/callback' => 'playlist#callback'
  get '/logout' => 'playlist#logout'
end

app/models/mood.rb
# == Schema Information
#
# Table name: moods
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Mood < ActiveRecord::Base
  belongs_to :users
  has_many :playlists
end

app/models/playlist.rb
# == Schema Information
#
# Table name: playlists
#
#  id         :integer          not null, primary key
#  playlist_1 :string(255)
#  playlist_2 :string(255)
#  playlist_3 :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Playlist < ActiveRecord::Base
  belongs_to :mood
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  password_digest :string(255)
#  user_id         :integer
#  first_name      :string(255)
#  last_name       :string(255)
#  email           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  has_secure_password
  has_many :moods
  has_many :playlists, :through => :moods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user

  private
  def authenticate_user
    if session[:user_id].present?
      @current_user = User.where(:id => session[:user_id]).first # Try to find a user but STAY CALM.
    end

    if @current_user.nil?
      session[:user_id] = nil
    end
  end
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  def index
    @moods = Mood.all
  end

  def show
    @mood = Mood.where(:name => params[:id].capitalize).first
    access_token = session[:at]
    access_token_secret = session[:ats]
    # raise params.inspect
      if access_token and access_token_secret
        rdio = Rdio.new(["wckdv2pub6av9q5fgs22br49", "e8M57wnN4h"],
                    [access_token, access_token_secret])

        @currentUser = rdio.call('currentUser')['result']
        @playlists = rdio.call('getPlaylists')['result']['owned']
        # raise params.inspect
      else
        redirect_to user_login_path
      end
    end
end

app/controllers/playlist_controller.rb
require 'rdio'

# :consumer_key => :wckdv2pub6av9q5fgs22br49, :consumer_secret => :e8M57wnN4h

class PlaylistController < ApplicationController
  def songs
    # Initialize new Rdio Client
  access_token = session[:at]
  access_token_secret = session[:ats]
  if access_token and access_token_secret
    rdio = Rdio.new(["wckdv2pub6av9q5fgs22br49", "e8M57wnN4h"],
                    [access_token, access_token_secret])

    @currentUser = rdio.call('currentUser')['result']
    @playlists = rdio.call('getPlaylists')['result']['owned']
    end
  end

  def login
    session.clear
    # begin the authentication process
    rdio = Rdio.new(["wckdv2pub6av9q5fgs22br49", "e8M57wnN4h"])
    callback_url = (URI.join request.url, '/callback').to_s
    url = rdio.begin_authentication(callback_url)
    # save our request token in the session
    session[:rt] = rdio.token[0]
    session[:rts] = rdio.token[1]
    # go to Rdio to authenticate the app
    redirect_to url
  end

  def callback
    # get the state from cookies and the query string
    request_token = session[:rt]
    request_token_secret = session[:rts]
    verifier = params[:oauth_verifier]
    # make sure we have everything we need
    if request_token and request_token_secret and verifier
      # exchange the verifier and request token for an access token
      rdio = Rdio.new(["wckdv2pub6av9q5fgs22br49", "e8M57wnN4h"],
                      [request_token, request_token_secret])
      rdio.complete_authentication(verifier)
      # save the access token in cookies (and discard the request token)
      session[:at] = rdio.token[0]
      session[:ats] = rdio.token[1]
      session.delete(:rt)
      session.delete(:rts)
      # go to the home page
      redirect_to('/')
    else
    # we're missing something important
      redirect_to('/logout')
    end
  end

  def logout
    session.clear
    redirect_to root_path
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new

  end

  def create
    user = User.find_by(:username => params[:username])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      # raise params.inspect
      redirect_to root_path
    else
      flash[:notice] = "Invalid login. Please try again."
      redirect_to user_login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :check_if_logged_in, :except => [:new, :create]
  # before_action :check_if_admin, :only => [:index]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  # def destroy
  #   @user = User.find params[:id]
  #   @user.destroy
  #   redirect_to root_path
  # end

  def edit
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    user.update user_params
    redirect_to root_path
  end

  def home
  #   session.clear
  #   # begin the authentication process
  #   rdio = Rdio.new(["wckdv2pub6av9q5fgs22br49", "e8M57wnN4h"])
  #   callback_url = (URI.join request.url, '/callback').to_s
  #   url = rdio.begin_authentication(callback_url)
  #   # save our request token in the session
  #   session[:rt] = rdio.token[0]
  #   session[:rts] = rdio.token[1]
  #   # go to Rdio to authenticate the app

  #   # get the state from cookies and the query string
  #   request_token = session[:rt]
  #   request_token_secret = session[:rts]
  #   verifier = params[:oauth_verifier]
  #   # make sure we have everything we need

  #     # exchange the verifier and request token for an access token
  #     # rdio = Rdio.new(["wckdv2pub6av9q5fgs22br49", "e8M57wnN4h"],
  #                     # [request_token, request_token_secret])
  #     rdio.complete_authentication(verifier)
  #     # save the access token in cookies (and discard the request token)
  #     session[:at] = rdio.token[0]
  #     session[:ats] = rdio.token[1]
  #     session.delete(:rt)
  #     session.delete(:rts)
  #     # go to the home page
  #     redirect_to('/')
  #   else
  #   # we're missing something important
  #     redirect_to('/logout')
  #   end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :user_id, :first_name, :last_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def smartnav
    links = ''
    if @current_user.try(:is_admin)
      links += "<li>" + link_to('View users', users_path) + "</li>"
    end

    if @current_user.present?
      links += "<li>"
      links += link_to('Logout ' + @current_user.username, user_login_path, :data => {:method => :delete, :confirm => 'Really logout?'})
      links += "</li>"
      links += "<li>"
      links += link_to('Edit ' + @current_user.username, edit_user_path(@current_user.id))
      links += "</li>"
    else
      links += "<li>#{ link_to('Sign up', new_user_path) }</li>"
      links += "<li>#{ link_to('Sign in', user_login_path) }</li>"
    end

    links
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moodytunes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div id="container">
  <nav id="main_links">
    <%= link_to('Home', root_path) %>
    <%= link_to('Login to Rdio', login_path) %>
    <%= link_to('Logout of Rdio', logout_path) %>
    <%== smartnav %>
  </nav>
  <%= yield %>
</div>


</body>
</html>

app/views/moods/index.html.erb
<% @moods.each do |mood| %>
<li><%= link_to(mood.name, mood) %></li>
<%end%>

app/views/moods/show.html.erb
<div class="moodname"><%= @mood.name %></div>
<div class="player"><iframe width="960" height="180" src="<%= @playlists.select {|playlist| playlist['name'] == @mood.name }.first["embedUrl"]%>"></iframe></div>

app/views/playlist/index.html.erb
<h1>homepage</h1>

    <h4>Rdio</h4>
    <a href="/login">Log into Rdio</a>
    <p><%= @currentUser["firstName"] %></p>
    <div class="player"><iframe width="1020" height="120" src="<%= @playlists.first["embedUrl"] %>" frameborder="0"></iframe></div>

app/views/session/new.html.erb
<div id="login_field">
  <%= form_tag '/user_login' do %>
    <%= label_tag 'username: ' %>
    <%= text_field_tag 'username', nil, :autofocus => true %>

    <%= label_tag 'password: ' %>
    <%= password_field_tag 'password' %>

    <%= button_tag 'Login' %>

  <% end %>
</div>

app/views/users/_form.html.erb
<div id="form_inputs">
  <%= form_for @user do |f| %>
    <h3>Username and Password</h3>
      <p>
        <%= f.label :username, "Username: " %>
        <%= f.text_field :username, :autofocus => true %>
      </p>

      <p>
        <%= f.label :password, "Password: " %>
        <%= f.password_field :password %>
        <%= f.label :password_confirmation, "Confirm: " %>
        <%= f.password_field :password_confirmation %>
      </p>

      <hr>
    <h3>Other Information</h3>
      <p>
        <%= f.label :first_name, "First Name: " %>
        <%= f.text_field :first_name %>
      </p>

      <p>
        <%= f.label :last_name, "Last Name: " %>
        <%= f.text_field :last_name %>
      </p>

      <p>
        <%= f.label :email, "Email: " %>
        <%= f.text_field :email %>
      </p>
        <%= f.button %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>Update User</h2>
<div id="inputs">
  <%= render :partial => 'form' %>
</div>

app/views/users/home.html.erb
<h1>MoodyTunes</h1>
<hr>

<% if @current_user.present? %>
    <!-- <h2>Select your Mood!!</h2> -->
    <div id="mood_list">
      <ul>
        <li><%= link_to('Happy', '/moods/happy') %></li>
        <li><%= link_to('Sad', '/moods/sad') %></li>
        <li><%= link_to('Rage', '/moods/rage') %></li>
        <li><%= link_to('Anger', '/moods/anger') %></li>
        <li><%= link_to('Hysteria', '/moods/hysteria') %></li>
        <li><%= link_to('Boredom', '/moods/boredom') %></li>
        <li><%= link_to('Pensive', '/moods/pensive') %></li>
        <li><%= link_to('Melancholy', '/moods/melancholy') %></li>
        <li><%= link_to('Elated', '/moods/elated') %></li>
        <li><%= link_to('Tired', '/moods/tired') %></li>
        <li><%= link_to('Adventure', '/moods/adventure') %></li>
        <li><%= link_to('Party', '/moods/party') %></li>
        <li><%= link_to('Hateful', '/moods/hateful') %></li>
        <li><%= link_to('Drunk', '/moods/drunk') %></li>
        <li><%= link_to('High', '/moods/high') %></li>
        <li><%= link_to('Relaxed', '/moods/relaxed') %></li>
      </ul>
    </div>
<% else %>
    <h2><%= link_to("Please Sign in to continue..", user_login_path) %></h2>
    <hr>
<% end %>

app/views/users/new.html.erb
<h2>Create New User</h2>
<div id="inputs">
  <%= render :partial => 'form' %>
</div>